# Generated by Django 5.1.3 on 2024-11-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExpensesTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("description", models.CharField(max_length=300)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("transportation", "Transportation"),
                            ("utilities", "Utilities"),
                            ("entertainment", "Entertainment"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
