# Generated by Django 5.1.3 on 2024-12-02 21:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyBudgetLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("food", "Food"),
                            ("transportation", "Transportation"),
                            ("utilities", "Utilities"),
                            ("entertainment", "Entertainment"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("budgetLimit", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date", models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
