# Generated by Django 5.1.3 on 2024-12-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0004_alter_dailybudgetlimit_budget_limit_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailybudgetlimit",
            old_name="budget_limit",
            new_name="budget",
        ),
        migrations.RemoveField(
            model_name="dailybudgetlimit",
            name="category",
        ),
        migrations.RemoveField(
            model_name="dailybudgetlimit",
            name="date",
        ),
        migrations.RemoveField(
            model_name="dailybudgetlimit",
            name="percentage_spent",
        ),
        migrations.RemoveField(
            model_name="dailybudgetlimit",
            name="total_spent",
        ),
        migrations.AddField(
            model_name="dailybudgetlimit",
            name="cate",
            field=models.CharField(default="General", max_length=100),
        ),
    ]
