# Generated by Django 5.1.3 on 2024-12-03 00:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0005_rename_budget_limit_dailybudgetlimit_budget_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="dailybudgetlimit",
            old_name="budget",
            new_name="budget_limit",
        ),
    ]
