# Generated by Django 5.1.3 on 2024-12-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0006_rename_budget_dailybudgetlimit_budget_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="expensestracker",
            name="bill_image",
            field=models.ImageField(blank=True, null=True, upload_to="bill_images/"),
        ),
    ]
